services:
  - type: web
    name: meu-blog
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn meusite.wsgi:application
